version: "2"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  digester:
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    build:
      context: ./reddit_mailer/digester
    image: python:3.5.1-slim
    ports:
      - 8000:8000
    command: bash -c "./scripts/wait_for_rabbitmq.sh && nameko run digester --broker amqp://guest:guest@rabbitmq"
